# to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           yarn: true
#           store_artifacts: true
#           record: true

version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    # env:
    #   CYPRESS_RECORD_KEY: 445d43ee-5f46-4144-b428-286de6535c1c
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: "Setup custom environment variables"
          command: echo 'export CYPRESS_RECORD_KEY="445d43ee-5f46-4144-b428-286de6535c1c"' >> $BASH_ENV
      - run: $(yarn bin)/cypress run --record