# to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           yarn: true
#           store_artifacts: true
#           record: true

version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/app
    steps:
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: $(yarn bin)/cypress run --record --key 445d43ee-5f46-4144-b428-286de6535c1c