# to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           yarn: true
#           store_artifacts: true
#           record: true

version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:8
      - working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run: npx cypress run --record --key 445d43ee-5f46-4144-b428-286de6535c1c